In [7]:
import statsmodels.tools.eval_measures as sm
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import glob
import os

#### 1. Poverty Profiles 2020-2022

In [105]:
df_age = pd.read_csv('poverty_profile_age_2020-2022.csv')

In [106]:
df_edu = pd.read_csv('./poverty_profile_education_2020-2022.csv')

In [107]:
df_econ = pd.read_csv('./poverty_profile_economic_2020-2022.csv')

In [108]:
df_employ = pd.read_csv('./poverty_profile_employment_2020-2022.csv')

In [109]:
df_household = pd.read_csv('./poverty_profile_household_2020-2022.csv')

In [110]:
df_tenure = pd.read_csv('./poverty_profile_tenure_2020-2022.csv')

In [20]:
def process_data(df, merge_columns):
    
    df.columns = df.columns.str.lower()
    
    label1 = 'At Risk of Poverty Rate'
    label2 = 'At Risk of Poverty Rate after rent and mortgage interest'
    
    df1 = df[df['statistic label'] == label1]
    df2 = df[df['statistic label'] == label2]
    
    df1.rename(columns={'value': f'{label1}' }, inplace=True)
    df2.rename(columns={'value': f'{label2}' }, inplace=True)
    
    df1 = df1.drop(columns=['unit', 'statistic label'])
    df2 = df2.drop(columns=['unit', 'statistic label'])
    
    df_full = df1.merge(df2, how='outer', on=merge_columns)
    df_full.columns = df_full.columns.str.lower()
    df_full.rename(columns={'at risk of poverty rate':'at risk of poverty'}, inplace=True)
    return df_full

merge_columns_age = ['year', 'age group']
merge_columns_edu = ['year', 'highest level of education completed']
merge_columns_econ = ['year', 'principal economic status']
merge_columns_employ = ['year', 'number of persons at work in the household']
merge_columns_household = ['year', 'household composition']
merge_columns_tenure = ['year', 'tenure status']

merged_df_age = process_data(df_age, merge_columns_age)
merged_df_edu = process_data(df_edu, merge_columns_edu)
merged_df_econ = process_data(df_econ, merge_columns_econ)
merged_df_employ = process_data(df_employ, merge_columns_employ)
merged_df_household = process_data(df_household, merge_columns_household)
merged_df_tenure = process_data(df_tenure, merge_columns_tenure)

In [118]:
merged_df_age.to_csv('poverty_age_2020_2022.csv')

In [119]:
merged_df_edu.to_csv('poverty_edu_2020_2022.csv')

In [120]:
merged_df_econ.to_csv('poverty_econ_2020_2022.csv')

In [121]:
merged_df_employ.to_csv('poverty_employ_2020_2022.csv')

In [122]:
merged_df_household.to_csv('poverty_household_2020_2022.csv')

In [123]:
merged_df_tenure.to_csv('poverty_tenure_2020_2022.csv')

#### Above we can see that the data is split into those generally at risk of poverty, and those at risk of poverty once their housing costs have been paid out. This indicates a section of the population who have the capacity for a mortgage/rental contract but are still living below the poverty line.

#### 2. Poverty Profiles 2006-2019

In [187]:
ls

Pivot Tables/                         poverty_profile_employment.csv
Raw Data/                             poverty_profile_household.csv
income_poverty_age_2004-2019.csv      poverty_profile_tenure_2006-2018.csv
poverty_profile_age_2006-2019.csv     poverty_profile_tenure_2019.csv
poverty_profile_economic.csv          poverty_rate_age_2008-2019.csv
poverty_profile_education.csv

In [56]:
pov_age = pd.read_csv('./poverty_profile_age_2006-2019.csv')

In [65]:
pov_econ = pd.read_csv('./poverty_profile_economic.csv')

In [67]:
pov_edu = pd.read_csv('./poverty_profile_education.csv')

In [87]:
pov_employ = pd.read_csv('./poverty_profile_employment.csv')

In [60]:
pov_household = pd.read_csv('./poverty_profile_household.csv')

In [88]:
pov_tenure = pd.read_csv('./poverty_profile_tenure_2006-2018.csv')

In [90]:
def process_data(df, merge_columns):
    
    df.columns = df.columns.str.lower()
    
    label1 = 'Profile of the Population'
    label2 = 'At Risk of Poverty'
    label3 = 'Deprivation Rate'
    label4 = 'In Consistent Poverty'
    
    df1 = df[df['statistic label'] == label1]
    df2 = df[df['statistic label'] == label2]
    df3 = df[df['statistic label'] == label3]
    df4 = df[df['statistic label'] == label4]
    
    df1.rename(columns={'value': f'{label1}' }, inplace=True)
    df2.rename(columns={'value': f'{label2}' }, inplace=True)
    df3.rename(columns={'value': f'{label3}' }, inplace=True)
    df4.rename(columns={'value': f'{label4}' }, inplace=True)
    
    df1 = df1.drop(columns=['unit', 'statistic label'])
    df2 = df2.drop(columns=['unit', 'statistic label'])
    df3 = df3.drop(columns=['unit', 'statistic label'])
    df4 = df4.drop(columns=['unit', 'statistic label'])
    
    df_temp = df1.merge(df2, how='outer', on=merge_columns)
    df_half = df_temp.merge(df3, how='outer', on=merge_columns)
    df_full = df_half.merge(df4, how='outer', on=merge_columns)
    df_full.columns = df_full.columns.str.lower()
    return df_full

merge_columns_age = ['year', 'age group']
merge_columns_edu = ['year', 'highest level of education completed']
merge_columns_econ = ['year', 'principal economic status']
merge_columns_employ = ['year', 'number of people at work']
merge_columns_household = ['year', 'household composition']
merge_columns_tenure = ['year', 'tenure status']

merged_pov_age = process_data(pov_age, merge_columns_age)
merged_pov_edu = process_data(pov_edu, merge_columns_edu)
merged_pov_econ = process_data(pov_econ, merge_columns_econ)
merged_pov_employ = process_data(pov_employ, merge_columns_employ)
merged_pov_household = process_data(pov_household, merge_columns_household)
merged_pov_tenure = process_data(pov_tenure, merge_columns_tenure)

/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={'value': f'{label3}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_37657/35481285.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.rename(columns={'value': f'{label4}' }, inplace=True)

In [95]:
merged_pov_age.to_csv('./poverty_age_2006_2019.csv')

In [96]:
merged_pov_econ.to_csv('./poverty_econ_2006_2019.csv')

In [97]:
merged_pov_edu.to_csv('./poverty_edu_2006_2019.csv')

In [98]:
merged_pov_employ.to_csv('./poverty_employ_2006_2019.csv')

In [99]:
merged_pov_household.to_csv('./poverty_household_2006_2019.csv')

In [100]:
merged_pov_tenure.to_csv('./poverty_tenure_2006_2019.csv')

### 3. Making as many values consistent as possible between datasets, to enable ease of investigation

In [130]:
merged_df_econ['principal economic status'].unique()

array(['Employed', 'Unemployed', 'Retired',
       'Unable to work due to long-standing health problems',
       'Student, pupil', 'Fulfilling domestic tasks'], dtype=object)

In [141]:
merged_df_econ.rename(columns={'Unable to work due to long-standing health problems':'Unfit',
                              'Student, pupil':'Student',
                             'Fulfilling domestic tasks':'Domestic'}, inplace=True)

,year,principal economic status,at risk of poverty,at risk of poverty rate after rent and mortgage interest
0,2020,Employed,6.5,10.4
1,2020,Unemployed,33.2,45.7
2,2020,Retired,9.8,12.6
3,2020,Unable to work due to long-standing health pro...,33.4,46.6
4,2020,"Student, pupil",20.3,25.1
5,2020,Fulfilling domestic tasks,20.7,30.1
6,2021,Employed,4.4,8.9
7,2021,Unemployed,23.2,41.0
8,2021,Retired,11.8,15.2
9,2021,Unable to work due to long-standing health pro...,39.1,53.8
10,2021,"Student, pupil",17.4,26.2
11,2021,Fulfilling domestic tasks,19.5,27.3
12,2022,Employed,5.8,12.4
13,2022,Unemployed,35.6,61.8
14,2022,Retired,19.1,22.1
15,2022,Unable to work due to long-standing health pro...,35.2,51.5
16,2022,"Student, pupil",13.7,21.8
17,2022,Fulfilling domestic tasks,23.8,31.3

In [158]:
merged_df_econ.to_csv('poverty_econ_2020_2022.csv')

In [127]:
merged_pov_econ.rename(columns={'At work':'Employed',
                                'Engaged on home duties': 'Domestic',
                                'Unable to work due to permanent sickness/disability' : 'Unfit'}, inplace=True)

In [159]:
merged_pov_econ.to_csv('./poverty_econ_2006_2019.csv')

In [142]:
merged_df_employ.rename(columns={'number of persons at work in the household':'number of persons employed'}, inplace=True)

,year,number of persons employed,at risk of poverty,at risk of poverty rate after rent and mortgage interest
0,2020,No person,29.4,39.4
1,2020,1 person,15.6,24.7
2,2020,2 persons,4.9,8.0
3,2020,3 or more persons,4.0,5.2
4,2021,No person,29.0,43.1
5,2021,1 person,12.6,21.4
6,2021,2 persons,3.0,6.6
7,2021,3 or more persons,3.6,5.6
8,2022,No person,34.6,45.9
9,2022,1 person,15.9,30.5
10,2022,2 persons,4.0,9.2
11,2022,3 or more persons,2.4,5.4

In [160]:
merged_df_employ.to_csv('poverty_employ_2020_2022.csv')

In [137]:
merged_pov_employ.rename(columns={'number of people at work':'number of persons employed'}, inplace=True)

In [157]:
merged_pov_employ.to_csv('./poverty_employ_2006_2019.csv')

In [15]:
poverty_percentage = pd.read_csv('./income_poverty_age_2004-2019.csv')
poverty_percentage

,Statistic Label,Year,Age Group,UNIT,VALUE
0,Median Real Household Disposable Income,2004,0 - 17 years,Euro,NaN
1,Median Real Household Disposable Income,2004,18 - 64 years,Euro,43948.0
2,Median Real Household Disposable Income,2004,65 years and over,Euro,18461.0
3,Median Real Household Disposable Income,2005,0 - 17 years,Euro,NaN
4,Median Real Household Disposable Income,2005,18 - 64 years,Euro,44557.0
...,...,...,...,...,...
523,Consistent Poverty Rate,2018,18 - 64 years,%,5.6
524,Consistent Poverty Rate,2018,65 years and over,%,1.7
525,Consistent Poverty Rate,2019,0 - 17 years,%,8.1
526,Consistent Poverty Rate,2019,18 - 64 years,%,5.1
527,Consistent Poverty Rate,2019,65 years and over,%,2.3

In [16]:
poverty_percentage['Statistic Label'].unique()

array(['Median Real Household Disposable Income',
       'Mean Real Household Disposable Income',
       'Median Nominal Household Disposable Income',
       'Mean Nominal Household Disposable Income',
       'Median Equivalised Real Disposable Income',
       'Mean Equivalised Real Disposable Income',
       'Median Equivalised Nominal Disposable Income',
       'Mean Equivalised Nominal Disposable Income',
       'At Risk of Poverty Rate', 'Deprivation Rate',
       'Consistent Poverty Rate'], dtype=object)

In [17]:
poverty_percentage = poverty_percentage[
    (poverty_percentage['Statistic Label'] == 'At Risk of Poverty Rate')|(poverty_percentage['Statistic Label'] == 'Consistent Poverty Rate')]

In [24]:
poverty_percentage

             statistic label  year          age group unit  value
384  At Risk of Poverty Rate  2004       0 - 17 years    %   22.7
385  At Risk of Poverty Rate  2004      18 - 64 years    %   16.6
386  At Risk of Poverty Rate  2004  65 years and over    %   27.1
387  At Risk of Poverty Rate  2005       0 - 17 years    %   22.9
388  At Risk of Poverty Rate  2005      18 - 64 years    %   16.1
..                       ...   ...                ...  ...    ...
523  Consistent Poverty Rate  2018      18 - 64 years    %    5.6
524  Consistent Poverty Rate  2018  65 years and over    %    1.7
525  Consistent Poverty Rate  2019       0 - 17 years    %    8.1
526  Consistent Poverty Rate  2019      18 - 64 years    %    5.1
527  Consistent Poverty Rate  2019  65 years and over    %    2.3

[96 rows x 5 columns]

In [30]:
def process_data(df, merge_columns):
    
    df.columns = df.columns.str.lower()
    
    label1 = 'At Risk of Poverty Rate'
    label2 = 'Consistent Poverty Rate'
    
    df1 = df[df['statistic label'] == label1]
    df2 = df[df['statistic label'] == label2]
    
    df1.rename(columns={'value': f'{label1}' }, inplace=True)
    df2.rename(columns={'value': f'{label2}' }, inplace=True)
    
    df1 = df1.drop(columns=['unit', 'statistic label'])
    df2 = df2.drop(columns=['unit', 'statistic label'])
    
    df_full = df1.merge(df2, how='outer', on=merge_columns)
    
    df_full.columns = df_full.columns.str.lower()
    return df_full

merge_columns_age = ['year', 'age group']

In [31]:
merged_poverty_percentage = process_data(poverty_percentage, merge_columns_age)

/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_59482/2032372115.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'value': f'{label1}' }, inplace=True)
/var/folders/fq/w4n1nx9n5flfw6tv_nzn8kyr0000gn/T/ipykernel_59482/2032372115.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'value': f'{label2}' }, inplace=True)

In [33]:
merged_poverty_percentage.to_csv('./poverty_percentage_2004_2019.csv')